Automate grafana tunnel
tetrateio/tetrate-service-bridge-sandbox pull request #210
Opened 2023-01-12 18:50 UTC by gonzaloserrano

2023-01-12 18:52 UTC, gonzaloserrano commented on modules/addons/grafana/main.tf
> +resource "local_file" "ssh_tunnel" {
self-review: now that I think this should be called port-forward instead of ssh-tunnel 🤔

2023-01-12 21:09 UTC, nacx commented
JFYI in case you haven't seen it, you can set these two values in your root `.tfvars` file:
```json
"grafana_service_type": "LoadBalancer",
"argocd_service_type": "LoadBalancer",
```
and those services will have a public IP allocated so that you don't need to port-forward.

2023-01-12 21:29 UTC, smarunich commented
Please lets limit the number of custom tools/overlays such as and lets use the port type instead, for the scripts like that lets not overload the tf.

2023-01-12 21:35 UTC, smarunich requested changes
-

2023-01-13 09:12 UTC, gonzaloserrano commented
Fair enough! 👍

2023-01-13 09:12 UTC, closed without merging